# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop1" ]
  pull_request:
    branches: [ "develop1" ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript # Here the path to the folder where package-lock.json is located.
    strategy:
      matrix:
        node-version: [14.x]
    #    node-version: [14.x, 16.x]
    #    node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: pwd 0
      run: pwd
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
    #    cache-dependency-path: javascript/package.json
    #- name: run npm commands
    #  run: | 
    #    pwd
    #    npm install
    #    npm run build --if-present
    #    npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./javascript
        push: true
        #tags: pingkunga/w91010_${{ matrix.node-version }}:latest
        #tags: pingkunga/w91010:latest
        tags: pingkunga/w91010:${{ github.sha }}