# CI CD 
# For master branch
# 1. Retag container image and push to docker hub
# 2. Notification by email

name: NODE_MAIN

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./javascript # Here the path to the folder where package-lock.json is located.
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Get Image Name & Tag
          id: Replace_Docker_Image
          uses: mikefarah/yq@master
          with:
            cmd: imagenametag="$imagenametag" yq -r '.spec.template.spec.containers.[0].image' javascript/manifest/dev/pingw91010.yaml
    
        #https://stackoverflow.com/a/76371212/20000255
        - name : Set ENV
          run: |
            echo "Test    $imagenametag"
            echo $imagenametag
            echo "IMAGE_NAME=$imagenametag" >> $GITHUB_ENV

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        #https://github.com/marketplace/actions/docker-metadata-action
        #Extract Docker Image Metadata
        - name: Extract Docker Image Metadata
          id: docker_meta
          uses: docker/metadata-action@v3
          with:
            images: ${{ env.IMAGE_NAME }}
            #all: true
            tags: |
              type=semver,pattern={{version}}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            #context: .
            #push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
